### ISSUE TITLE
Mono on *-nix support

### ISSUE THREAD

**Issue by semack** [GlenConway/ConsoleUI#1]
Hi Glen,
First of all thank you for the work, your lib seems that I am looking for ;) 
I see you use windows platform invocation for drawings, is it possible to create cross-platform version of the library?
Thanks!

**Comment by GlenConway** [comment]
Hi Andriy - did you check out MonoCurses yet?  I built this library for a very specific use case but would love to explore cross-platform capabilities at some future point.

Here's the link if you haven't already checked it out:
[http://www.mono-project.com/docs/tools+libraries/libraries/monocurses/](http://www.mono-project.com/docs/tools+libraries/libraries/monocurses/)

**Comment by semack** [comment]
Thank you for pointing!

**Comment by GlenConway** [comment]
No problem!
